spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC
    username: user
    password: password
  
  jpa:
    hibernate:
      ddl-auto: update

  
  security:
    user:
      name: "admin"
      password: "admin"